# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en/
  title: Damla & Endre
  params:
    description: 👋 Welcome to our wedding website! 👋
  menu:
    main:
      - name: Home
        url: https://damlaendre.github.io/sepsi/en/#top
        weight: 10
      - name: RSVP
        url: https://forms.gle/2Eq7oZhvQa5VHxc87/
        weight: 20
      - name: Schedule
        url: https://damlaendre.github.io/sepsi/en/#schedule
        weight: 30
      - name: Venue
        url: https://damlaendre.github.io/sepsi/en/#venue
        weight: 40
      - name: Accommodation
        url: https://damlaendre.github.io/sepsi/en/#accommodation
        weight: 50
      - name: Transportation
        url: https://damlaendre.github.io/sepsi/en/travel/
        weight: 60
      - name: Contact
        url: https://damlaendre.github.io/sepsi/en/#contact
        weight: 70
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
hu:
  languageCode: hu
  contentDir: content/hu/
  title: Damla & Endre
  params:
    description: 👋 Üdvözlünk eskűvői honlapunkon! 👋
  #menu:
#main:
#- name: Főoldal
#url: /#top
#weight: 10
#- name: Részvétel
#url: https://forms.gle/SU54TxtCUmC9obbq8
#weight: 20
#- name: Program
#url: /#schedule
#weight: 30
#- name: Helyszín
#url: /#venue
#weight: 40
#- name: Szálláshely
#url: /#accommodation
#weight: 50
#- name: Elérhetőség
#url: /#contact
#weight: 70
