# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en/
  title: Damla & Endre
  params:
    description: 👋 Welcome to our wedding website! 👋
  menu:
    main:
      - name: Home
        url: https://damlaendre.github.io/ist/#top
        weight: 10
      - name: RSVP
        url: https://forms.gle/kxCG22e8vi8JcfM86
        weight: 20
      - name: Schedule
        url: https://damlaendre.github.io/ist/#schedule
        weight: 30
      - name: Venue
        url: https://damlaendre.github.io/ist/#venue
        weight: 40
      - name: Accommodation
        url: https://damlaendre.github.io/ist/#accommodation
        weight: 50
      - name: Transportation
        url: https://damlaendre.github.io/ist/travel/
        weight: 60
      - name: Istanbul
        url: https://damlaendre.github.io/ist/istanbul/
        weight: 70
      - name: Attire
        url: https://damlaendre.github.io/ist/#attire
        weight: 80
      - name: Gift giving
        url: https://damlaendre.github.io/ist/#gift
        weight: 90
      - name: Photos
        url: https://damlaendre.github.io/ist/#photos
        weight: 100
      - name: Contact
        url: https://damlaendre.github.io/ist/#contact
        weight: 110
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
tr:
  languageCode: tr
  contentDir: content/tr/
  title: Damla & Endre
  params:
    description: 👋 Düğünümüze hoş geldiniz! 👋
  #menu:
#main:
#- name: Főoldal
#url: /#top
#weight: 10
#- name: Részvétel
#url: https://forms.gle/SU54TxtCUmC9obbq8
#weight: 20
#- name: Program
#url: /#schedule
#weight: 30
#- name: Helyszín
#url: /#venue
#weight: 40
#- name: Szálláshely
#url: /#accommodation
#weight: 50
#- name: Elérhetőség
#url: /#contact
#weight: 70
