# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: RSVP
    url: https://forms.gle/2Eq7oZhvQa5VHxc87/
    weight: 20
  - name: Schedule
    url: /#schedule
    weight: 30
  - name: Venue
    url: /#venue
    weight: 40
  - name: Accommodation
    url: /#accommodation
    weight: 50
  - name: Transportation
    url: /travel/
    weight: 60
  - name: Contact
    url: /#contact
    weight: 70