# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: https://damlaendre.github.io/sepsi/en/#top
    weight: 10
  - name: RSVP
    url: https://forms.gle/2Eq7oZhvQa5VHxc87/
    weight: 20
  - name: Schedule
    url: https://damlaendre.github.io/sepsi/en/#schedule
    weight: 30
  - name: Venue
    url: https://damlaendre.github.io/sepsi/en/#venue
    weight: 40
  - name: Accommodation
    url: https://damlaendre.github.io/sepsi/en/#accommodation
    weight: 50
  - name: Transportation
    url: https://damlaendre.github.io/sepsi/en/travel/
    weight: 60
  - name: Contact
    url: https://damlaendre.github.io/sepsi/en/#contact
    weight: 70