# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Anasayfa
    url: /#top
    weight: 10
  - name: Katılım
    url: https://forms.gle/ZPfoa3HFsrnePHmeA
    weight: 20
  - name: Program
    url: /#schedule
    weight: 30
  - name: Mekan
    url: /#venue
    weight: 40
  - name: İletişim
    url: /#contact
    weight: 50
    